import "dotenv/config";

export const env = {
  port: Number(process.env.PORT ?? 4000),
  host: process.env.HOST ?? "0.0.0.0",
  databaseUrl: process.env.DATABASE_URL ?? "",
  jwtSecret: process.env.JWT_SECRET ?? "viraflow-dev-secret",
  supabaseUrl: process.env.SUPABASE_URL ?? "",
  supabaseAnonKey: process.env.SUPABASE_ANON_KEY ?? "",
  firebaseProjectId: process.env.FIREBASE_PROJECT_ID ?? "",
  firebaseClientEmail: process.env.FIREBASE_CLIENT_EMAIL ?? "",
  firebasePrivateKey: process.env.FIREBASE_PRIVATE_KEY ?? "",
  firebaseStorageBucket: process.env.FIREBASE_STORAGE_BUCKET ?? "",
  firebaseWebApiKey: process.env.FIREBASE_WEB_API_KEY ?? "AIzaSyAljVqvu5c2cq9m9uTBuvQZ1oYFFjkI5B8",
  cloudinaryCloudName: process.env.CLOUDINARY_CLOUD_NAME ?? "",
  cloudinaryApiKey: process.env.CLOUDINARY_API_KEY ?? "",
  cloudinaryApiSecret: process.env.CLOUDINARY_API_SECRET ?? "",
  cloudinaryUploadFolder: process.env.CLOUDINARY_UPLOAD_FOLDER ?? "viraflow",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  stripeSuccessUrl: process.env.STRIPE_SUCCESS_URL ?? "",
  stripeCancelUrl: process.env.STRIPE_CANCEL_URL ?? "",
  stripePriceWeekly: process.env.STRIPE_PRICE_WEEKLY ?? "",
  stripePriceMonthly: process.env.STRIPE_PRICE_MONTHLY ?? "",
  stripePriceYearly: process.env.STRIPE_PRICE_YEARLY ?? "",
  stripePriceBoostStarter: process.env.STRIPE_PRICE_BOOST_STARTER ?? "",
  stripePriceBoostGrowth: process.env.STRIPE_PRICE_BOOST_GROWTH ?? "",
  stripePriceBoostViral: process.env.STRIPE_PRICE_BOOST_VIRAL ?? "",
  openAiApiKey: process.env.OPENAI_API_KEY ?? "",
  openAiModerationModel: process.env.OPENAI_MODERATION_MODEL ?? "omni-moderation-latest",
  openAiTextModel: process.env.OPENAI_TEXT_MODEL ?? "gpt-5.4",
  openAiImageModel: process.env.OPENAI_IMAGE_MODEL ?? "gpt-image-1.5",
  openAiVideoModel: process.env.OPENAI_VIDEO_MODEL ?? "sora-2",
  openAiVoiceModel: process.env.OPENAI_VOICE_MODEL ?? "gpt-4o-mini-tts",
  openAiTranscriptionModel: process.env.OPENAI_TRANSCRIPTION_MODEL ?? "whisper-1",
  openAiDefaultVoice: process.env.OPENAI_DEFAULT_VOICE ?? "coral",
};
